Only warn of rate-limits when using HF endpoint
huggingface/llm-ls pull request #58
Opened 2024-01-20 12:45 UTC by HennerM

I am trying the llm-vscode extension with llm-ls on a locally hosted endpoint (running a custom fine-tuned model), however the extension still gives a warning that I might get rate limited by HuggingFace.

Since inference doesn't run on a HuggingFace server this warning is not necessary.

2024-01-28 22:07 UTC, McPatate reviewed
Since we know have the adaptor setting, I'd rather check its value than doing so w/ the URL. Wdyt?

2024-02-04 20:05 UTC, HennerM commented
> Since we know have the adaptor setting, I'd rather check its value than doing so w/ the URL. Wdyt?

Yes good idea, I changed this to just check the adopter value now

2024-02-05 08:26 UTC, McPatate requested changes
Small nits on naming, we should be good to go!

2024-02-05 08:26 UTC, McPatate commented on crates/llm-ls/src/adaptors.rs
> +pub(crate) const DEFAULT_ADAPTOR: &str = HUGGING_FACE;
This should be an enum 🤔

I'll open a separate issue

2024-02-05 08:26 UTC, McPatate commented on crates/llm-ls/src/main.rs
> +const HUGGINGFACE_INFERENCE_HOSTNAME: &str = "api-inference.huggingface.co";
```suggestion
const HF_INFERENCE_API_HOSTNAME: &str = "api-inference.huggingface.co";
```

2024-02-05 08:26 UTC, McPatate commented on crates/llm-ls/src/main.rs
> +            let is_using_hf_inference = params.adaptor.as_ref().unwrap_or(&adaptors::DEFAULT_ADAPTOR.to_string()).as_str() == adaptors::HUGGING_FACE;
```suggestion
            let is_using_inference_api = params.adaptor.as_ref().unwrap_or(&adaptors::DEFAULT_ADAPTOR.to_string()).as_str() == adaptors::HUGGING_FACE;
```

2024-02-05 15:21 UTC, McPatate requested changes

2024-02-05 15:21 UTC, McPatate commented on crates/llm-ls/src/main.rs
> +            if params.api_token.is_none() && is_using_hf_inference {
```suggestion
            if params.api_token.is_none() && is_using_inference_api {
```
Should've added all suggestions sorry!

2024-02-05 15:21 UTC, McPatate commented on crates/llm-ls/src/main.rs
> +        format!("https://{HUGGINGFACE_INFERENCE_HOSTNAME}/models/{model}")
```suggestion
        format!("https://{HF_INFERENCE_API_HOSTNAME}/models/{model}")
```

2024-02-05 15:27 UTC, McPatate commented on crates/llm-ls/src/main.rs
> +            let is_using_inference_api = params.adaptor.as_ref().unwrap_or(&adaptors::DEFAULT_ADAPTOR.to_string()).as_str() == adaptors::HUGGING_FACE;
```suggestion
            let is_using_inference_api = params.adaptor.as_ref().unwrap_or_else(|| &adaptors::DEFAULT_ADAPTOR.to_owned()).as_str() == adaptors::HUGGING_FACE;
```

2024-02-05 15:36 UTC, McPatate commented on crates/llm-ls/src/main.rs
> +            let is_using_inference_api = params.adaptor.as_ref().unwrap_or_else(|| &adaptors::DEFAULT_ADAPTOR.to_owned()).as_str() == adaptors::HUGGING_FACE;
```suggestion
            let is_using_inference_api = params.adaptor.as_ref().unwrap_or(adaptors::DEFAULT_ADAPTOR).as_str() == adaptors::HUGGING_FACE;
```

2024-02-05 17:33 UTC, McPatate commented on crates/llm-ls/src/main.rs
> +            let is_using_inference_api = params.adaptor.as_ref().unwrap_or(adaptors::DEFAULT_ADAPTOR).as_str() == adaptors::HUGGING_FACE;
```suggestion
            let is_using_inference_api = params.adaptor.as_ref().unwrap_or(&adaptors::DEFAULT_ADAPTOR.to_owned()).as_str() == adaptors::HUGGING_FACE;
```

2024-02-05 20:05 UTC, merged